# Galaxy, Postgres
- src: galaxyproject.galaxy
  version: 0.12.0
- src: galaxyproject.postgresql
  version: 1.1.8
- src: galaxyproject.postgresql_objects
  version: 1.2.1
- src: galaxyproject.miniconda
  version: 0.3.4
# gxadmin (used in cleanup, and later monitoring.)
- src: galaxyproject.gxadmin
  version: 0.0.13
# automatic tool installation
- src: galaxyproject.galaxy-tools
  version: v0.3.0
# Singularity/Apptainer
- src: usegalaxy_eu.apptainer
  version: 0.0.1

