# Galaxy, Postgres
- src: galaxyproject.galaxy
  version: 0.11.1
- src: galaxyproject.postgresql
  version: 1.1.7
- src: galaxyproject.postgresql_objects
  version: 1.2.0
- src: galaxyproject.miniconda
  version: 0.3.1
# gxadmin (used in cleanup, and later monitoring.)
- src: galaxyproject.gxadmin
  version: 0.0.13
# automatic tool installation
- src: galaxyproject.galaxy-tools
  version: v0.3.0

