---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: el-7
    image: centos:7
  - name: el-8
    image: rockylinux:8
  - name: el-9
    image: rockylinux:9
  - name: ubuntu-focal
    image: ubuntu:focal
  - name: ubuntu-jammy
    image: ubuntu:jammy
  - name: ubuntu-lunar
    image: ubuntu:lunar
  - name: ubuntu-mantic
    image: ubuntu:mantic
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: true
  inventory:
    host_vars:
      el-7:
        ansible_python_interpreter: /usr/bin/python
      el-8:
        ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
